In [1]:
import pandas as pd

In [2]:
import numpy as np


In [8]:
d1 = pd.DataFrame({"key": ['a','b','c','c','d','e'],
                   "num1":range(6)})
d2 = pd.DataFrame({
    "key":["b","c","e","f"],
    "num2":range(4)})
print(d1)
print(d2)

  key  num1
0   a     0
1   b     1
2   c     2
3   c     3
4   d     4
5   e     5
  key  num2
0   b     0
1   c     1
2   e     2
3   f     3


In [9]:
#Merging tables
pd.merge(d1,d2)

key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

In [11]:
pd.merge(d1,d2,on ="key")

key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

In [15]:
d3 = pd.DataFrame({"key1": ['a','b','c','c','d','e'],
                   "num1":range(6)})
d4 = pd.DataFrame({
    "key2":["b","c","e","f"],
    "num2":range(4)})
print(d3)
print(d4)

  key1  num1
0    a     0
1    b     1
2    c     2
3    c     3
4    d     4
5    e     5
  key2  num2
0    b     0
1    c     1
2    e     2
3    f     3


In [18]:
pd.merge(d3,d4, left_on = "key1", right_on = "key2")

key1  num1 key2  num2
0    b     1    b     0
1    c     2    c     1
2    c     3    c     1
3    e     5    e     2

In [19]:
pd.merge(d1,d2,how = "outer")

key  num1  num2
0   a   0.0   NaN
1   b   1.0   0.0
2   c   2.0   1.0
3   c   3.0   1.0
4   d   4.0   NaN
5   e   5.0   2.0
6   f   NaN   3.0

In [20]:
pd.merge(d1,d2,how="left")

key  num1  num2
0   a     0   NaN
1   b     1   0.0
2   c     2   1.0
3   c     3   1.0
4   d     4   NaN
5   e     5   2.0

In [21]:
pd.merge(d1,d2,how="right")

key  num1  num2
0   b   1.0     0
1   c   2.0     1
2   c   3.0     1
3   e   5.0     2
4   f   NaN     3

In [22]:
pd.merge(d1,d2,how="inner")

key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

In [26]:
right = pd.DataFrame([[1,2],[3,4],[5,6]],
                    index = ["a","c","d"],
                     columns = ["Tom","Tim"]
                    )
left = pd.DataFrame([[7,8],[9,10],[11,12],[13,14]],
                    index = ["a","b","e","f"],
                     columns = ["Sam","Kim"]
                    )
print(right)
print(left)


   Tom  Tim
a    1    2
c    3    4
d    5    6
   Sam  Kim
a    7    8
b    9   10
e   11   12
f   13   14


In [32]:
pd.merge(right,left,
        right_index = True,
         left_index = True,
         how ="outer")

Tom  Tim   Sam   Kim
a  1.0  2.0   7.0   8.0
b  NaN  NaN   9.0  10.0
c  3.0  4.0   NaN   NaN
d  5.0  6.0   NaN   NaN
e  NaN  NaN  11.0  12.0
f  NaN  NaN  13.0  14.0

In [ ]:
#Join Operation

In [35]:
left.join(right)

Sam  Kim  Tom  Tim
a    7    8  1.0  2.0
b    9   10  NaN  NaN
e   11   12  NaN  NaN
f   13   14  NaN  NaN

In [45]:
df4 = pd.DataFrame([[1,3],[5,7],[9,11]],
                   index = ["a","b","f"],
                  columns=["Alex","Keta"])
df4

Alex  Keta
a     1     3
b     5     7
f     9    11

In [47]:
left.join([right,df4])

Sam   Kim  Tom  Tim  Alex  Keta
a   7.0   8.0  1.0  2.0   1.0   3.0
b   9.0  10.0  NaN  NaN   5.0   7.0
e  11.0  12.0  NaN  NaN   NaN   NaN
f  13.0  14.0  NaN  NaN   9.0  11.0

CONCATENATION ALONG AN AXIS

In [48]:
seq = np.arange(20).reshape(4,5)

In [49]:
seq

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [51]:
np.concatenate([seq,seq],axis = 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [54]:
np.concatenate([seq,seq],axis = 1)

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19]])

In [62]:
data1 = pd.Series([0,1],
                  index = ["a","b"])
data2 = pd.Series([2,3,4],
                  index = ["c","d","e"])
data3 = pd.Series([5,6],
                  index = ["f","g"])
print(data1)
print(data2)
print(data3)

a    0
b    1
dtype: int64
c    2
d    3
e    4
dtype: int64
f    5
g    6
dtype: int64


In [64]:
pd.concat([data1,data2,data3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [65]:
pd.concat([data1,data2,data3],axis = 1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [68]:
data4 = pd.Series([10,11,12],
                  index = ["a","b","c"])
data4

a    10
b    11
c    12
dtype: int64

In [72]:
pd.concat([data1,data4],axis=1,join="inner")

0   1
a  0  10
b  1  11

In [83]:
x = pd.concat([data1,data2,data4],
              keys= ["one","two","three"])

In [84]:
x

one    a     0
       b     1
two    c     2
       d     3
       e     4
three  a    10
       b    11
       c    12
dtype: int64

In [86]:
data1 = pd.DataFrame(np.random.randn(3,4),
                     columns = ["a","b","c","d"]
)
data2 = pd.DataFrame(np.random.randn(2,3),
                     columns = ["b","d","a"]
)


In [87]:
pd.concat([data1,data2])

a         b         c         d
0 -0.496885  0.727615 -0.891132 -0.359448
1  0.719176  0.506138 -0.990918  0.417977
2 -1.145396 -1.513644  0.517479  1.336480
0 -1.411854 -1.193241       NaN  0.635843
1 -0.639123  0.510939       NaN  0.777703

In [88]:
pd.concat([data1,data2],ignore_index=True)

a         b         c         d
0 -0.496885  0.727615 -0.891132 -0.359448
1  0.719176  0.506138 -0.990918  0.417977
2 -1.145396 -1.513644  0.517479  1.336480
3 -1.411854 -1.193241       NaN  0.635843
4 -0.639123  0.510939       NaN  0.777703

In [89]:
!pip install nycflights13

     ---------------------------------------- 8.7/8.7 MB 930.3 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for nycflights13: filename=nycflights13-0.0.3-py3-none-any.whl size=8732736 sha256=8fbeb05d8458fa2ae763110172403cdf229ab73c1591dc551ab94139b9c53c90
  Stored in directory: c:\users\sauga\appdata\local\pip\cache\wheels\45\69\2d\ef1024b231256499d8d8d414588fab2ea9bea42529be5c9c64
Successfully built nycflights13
